---
grafana:
  enabled: false
alertmanager:
  enabled: false
prometheus:
  prometheusSpec:
    scrapeInterval: "10s"
    serviceMonitorSelectorNilUsesHelmValues: false
    remoteWrite:
      - url: http://mimir-nginx.monitoring.svc.cluster.local:80/api/v1/push
    remoteWriteDashboards: true